services:
  app:
    build:
      context: .  # El contexto es el directorio raíz donde está el Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"  # Exponer el puerto 8000 para la aplicación Laravel
    volumes:
      - ./EduPro:/app  # Montamos el directorio local 'EduPro' dentro del contenedor
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gestion_proyectos_academicos
      - DB_USERNAME=root
      - DB_PASSWORD=m1_s3cr3t
    command: >
      bash -c "composer install && php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"
  
  db:
    build:
      context: ./db_config  # Ruta al Dockerfile de MariaDB
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=m1_s3cr3t
      - MYSQL_DATABASE=gestion_proyectos_academicos
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
